### ISSUE TITLE
npm install fails with npm 2.x

### ISSUE THREAD

**Issue by gesellix** [drone/drone-wall#33] opened 2016-03-05 21:40 UTC
I tried to build the drone-wall locally, so I needed to `npm install`. Sadly, I stumble upon this error:

```
366928 error Linux 4.1.18-boot2docker
366929 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
366930 error node v4.2.2
366931 error npm  v2.14.7
366932 error code EPEERINVALID
366933 error peerinvalid The package grunt-svg-sprite@1.1.2 does not satisfy its siblings' peerDependencies requirements!
366933 error peerinvalid Peer dominatr-grunt@6.1.2 wants grunt-svg-sprite@github:vokal/grunt-svg-sprite.git#8200979a0e
```

How do you perform a fresh install? Which node/npm version is recommended?

**Comment by Tathanen** [comment] 2016-03-05 21:51
Does this actually terminate your install?  There will probably be an error or two, I know I get python complaints when I install due to something somewhere wanting python, but it isn't required by the wall at all.

I have success with npm 3.x and node 4.x.

**Comment by bradrydzewski** [comment] 2016-03-05 21:57
I can confirm I'm able to build on my linux machine with npm 3.4 and node 4.2

**Comment by athieriot** [comment] 2016-03-05 22:00
The same issue happen for me with npm 2.14

**Comment by gesellix** [comment] 2016-03-05 22:00
I can also confirm that using npm 3.x seems to succeed. Right now I'm retrying in a clean container... thanks for the quick feedback!

**Comment by gesellix** [comment] 2016-03-05 22:01
If npm 2.x consistently fails, it would make sense to add a note in the README?

**Comment by Tathanen** [comment] 2016-03-05 22:01
Absolutely, I'll make a note of that if we determine this is indeed the issue.  @athieriot can you try updating your npm version?

**Comment by athieriot** [comment] 2016-03-05 22:02
Yup. npm 3 is doing the trick

**Comment by gesellix** [comment] 2016-03-05 22:06
@Tathanen Though my npm install is still running (slow connection), I regard this issue as resolved from my point of view - leaving it open for you as reminder to add a note in the README :-)

**Comment by Tathanen** [comment] 2016-03-05 22:08
Great!  I've added a note to the top of the local dev section in the readme, closing this issue as resolved.

**Closed by Tathanen** 2016-03-05 22:08 UTC
